name: nyc-taxi

schedule: "daily"

start_date: "2026-01-01"
default_connections:
  duckdb: duckdb-default
variables:
  # TODO: Define `taxi_types` as an array of strings with a sensible default.
  taxi_types:
    type: array  # should be: array
    items:
      type: string  # should be: string
    default: ["yellow"]  # e.g. ["yellow", "green"]
#   other_string_var: (optional) Add your own variable and use it in both Python and SQL assets.
#     type: string
#     default: "my_value"
